/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-05-05 20:00:12 UTC)
 * on 2015-05-12 at 10:20:22 UTC 
 * Modify at your own risk.
 */

package com.appspot.waldo_gcp.waldo.model;

/**
 * Model definition for ApplicationApisWaypointsMessagesWayPointsListResponse.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the waldo. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ApplicationApisWaypointsMessagesWayPointsListResponse extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String msg;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("next_cursor")
  private java.lang.String nextCursor;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("pre_cursor")
  private java.lang.String preCursor;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<ApplicationApisWaypointsMessagesWayPointResponseMessage> waypoints;

  static {
    // hack to force ProGuard to consider ApplicationApisWaypointsMessagesWayPointResponseMessage used, since otherwise it would be stripped out
    // see http://code.google.com/p/google-api-java-client/issues/detail?id=528
    com.google.api.client.util.Data.nullOf(ApplicationApisWaypointsMessagesWayPointResponseMessage.class);
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getMsg() {
    return msg;
  }

  /**
   * @param msg msg or {@code null} for none
   */
  public ApplicationApisWaypointsMessagesWayPointsListResponse setMsg(java.lang.String msg) {
    this.msg = msg;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNextCursor() {
    return nextCursor;
  }

  /**
   * @param nextCursor nextCursor or {@code null} for none
   */
  public ApplicationApisWaypointsMessagesWayPointsListResponse setNextCursor(java.lang.String nextCursor) {
    this.nextCursor = nextCursor;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPreCursor() {
    return preCursor;
  }

  /**
   * @param preCursor preCursor or {@code null} for none
   */
  public ApplicationApisWaypointsMessagesWayPointsListResponse setPreCursor(java.lang.String preCursor) {
    this.preCursor = preCursor;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<ApplicationApisWaypointsMessagesWayPointResponseMessage> getWaypoints() {
    return waypoints;
  }

  /**
   * @param waypoints waypoints or {@code null} for none
   */
  public ApplicationApisWaypointsMessagesWayPointsListResponse setWaypoints(java.util.List<ApplicationApisWaypointsMessagesWayPointResponseMessage> waypoints) {
    this.waypoints = waypoints;
    return this;
  }

  @Override
  public ApplicationApisWaypointsMessagesWayPointsListResponse set(String fieldName, Object value) {
    return (ApplicationApisWaypointsMessagesWayPointsListResponse) super.set(fieldName, value);
  }

  @Override
  public ApplicationApisWaypointsMessagesWayPointsListResponse clone() {
    return (ApplicationApisWaypointsMessagesWayPointsListResponse) super.clone();
  }

}
