/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-05-05 20:00:12 UTC)
 * on 2015-05-12 at 10:20:22 UTC 
 * Modify at your own risk.
 */

package com.appspot.waldo_gcp.waldo.model;

/**
 * Model definition for ApplicationApisWaypointsMessagesWayPointResponseMessage.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the waldo. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ApplicationApisWaypointsMessagesWayPointResponseMessage extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double best;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String created;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long generation;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long genomes;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> locations;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("object_name")
  private java.lang.String objectName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String thumbnail;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getBest() {
    return best;
  }

  /**
   * @param best best or {@code null} for none
   */
  public ApplicationApisWaypointsMessagesWayPointResponseMessage setBest(java.lang.Double best) {
    this.best = best;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCreated() {
    return created;
  }

  /**
   * @param created created or {@code null} for none
   */
  public ApplicationApisWaypointsMessagesWayPointResponseMessage setCreated(java.lang.String created) {
    this.created = created;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getGeneration() {
    return generation;
  }

  /**
   * @param generation generation or {@code null} for none
   */
  public ApplicationApisWaypointsMessagesWayPointResponseMessage setGeneration(java.lang.Long generation) {
    this.generation = generation;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getGenomes() {
    return genomes;
  }

  /**
   * @param genomes genomes or {@code null} for none
   */
  public ApplicationApisWaypointsMessagesWayPointResponseMessage setGenomes(java.lang.Long genomes) {
    this.genomes = genomes;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public ApplicationApisWaypointsMessagesWayPointResponseMessage setId(java.lang.String id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getLocations() {
    return locations;
  }

  /**
   * @param locations locations or {@code null} for none
   */
  public ApplicationApisWaypointsMessagesWayPointResponseMessage setLocations(java.util.List<java.lang.String> locations) {
    this.locations = locations;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getObjectName() {
    return objectName;
  }

  /**
   * @param objectName objectName or {@code null} for none
   */
  public ApplicationApisWaypointsMessagesWayPointResponseMessage setObjectName(java.lang.String objectName) {
    this.objectName = objectName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getThumbnail() {
    return thumbnail;
  }

  /**
   * @param thumbnail thumbnail or {@code null} for none
   */
  public ApplicationApisWaypointsMessagesWayPointResponseMessage setThumbnail(java.lang.String thumbnail) {
    this.thumbnail = thumbnail;
    return this;
  }

  @Override
  public ApplicationApisWaypointsMessagesWayPointResponseMessage set(String fieldName, Object value) {
    return (ApplicationApisWaypointsMessagesWayPointResponseMessage) super.set(fieldName, value);
  }

  @Override
  public ApplicationApisWaypointsMessagesWayPointResponseMessage clone() {
    return (ApplicationApisWaypointsMessagesWayPointResponseMessage) super.clone();
  }

}
